package com.gui;

import com.database.*;
import com.model.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Valar Morghulis
 */
public class Main extends javax.swing.JFrame {

    AnimalDAO dao;
    VetDAO vetDAO;
    /**
     * Creates new form MainFrame
     */
    public Main() {
        initComponents();
        dao = new AnimalDAO(); // Instantiate with your actual implementation
        vetDAO = new VetDAO(); // Instantiate with your actual implementation
    }

    JButton btnListAnimals, btnAddAnimal, btnAddSymptoms, btnShowVets;
    JPanel mainPanel, panelListAnimals, panelAddAnimal, panelAddSymptoms,panelVetList;
    JButton btnLogout;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListAnimals = new JButton("List Animals");
        btnAddAnimal = new JButton("Add Animal");
        btnAddSymptoms = new JButton("Add Symptoms");
        btnShowVets = new JButton("Show Vets");

        mainPanel = new JPanel();
        panelListAnimals = new JPanel();
        panelAddAnimal = new JPanel();
        panelAddSymptoms = new JPanel();
        panelVetList = new JPanel();

        btnLogout = new JButton("Log out");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CEPVET");

        applyButtonStyles(btnListAnimals);
        applyButtonStyles(btnAddAnimal);
        applyButtonStyles(btnAddSymptoms);
        applyButtonStyles(btnShowVets);


        btnListAnimals.addActionListener(e -> btnListAnimalsActionPerformed(e));
        btnAddAnimal.addActionListener(e -> btnAddAnimalActionPerformed(e));
        btnAddSymptoms.addActionListener(e -> btnAddSymptomsActionPerformed(e));
        btnShowVets.addActionListener(e -> btnShowVetsActionPerformed(e));

        btnLogout.addActionListener(e -> {
            // Add code to handle logout action
            // This could include closing the current window and opening a login window, or any other logout-related actions.
            JOptionPane.showMessageDialog(this, "Logout Successful", "Logout", JOptionPane.INFORMATION_MESSAGE);
            // Example: Opening a login window
            Login loginFrame = new Login();
            loginFrame.setVisible(true);
            // Close the current window
            this.dispose();
        });
        

        mainPanel.add(panelListAnimals, "Animal List");
        mainPanel.add(panelAddAnimal, "Add Animal");
        mainPanel.add(panelAddSymptoms, "Add Symptoms");
        mainPanel.add(panelVetList, "Vets");
    }


    private void applyButtonStyles(JButton button) {
        button.setBackground(new java.awt.Color(153, 102, 255));
        button.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 14));
        button.setForeground(new java.awt.Color(51, 51, 51));
    }

    private void btnListAnimalsActionPerformed(ActionEvent evt) {
        // Implement the action for btnListAnimals
        // Replace this with your actual implementation
        // Example: Assuming you have a method getAnimalList() in your data access object (dao)
        List<Animal> animals = AnimalDAO.getAllAnimals();
        StringBuilder animalListText = new StringBuilder("List of Animals:\n");

        for (Animal animal : animals) {
            animalListText.append("ID: ").append(animal.getAnimalId())
                    .append(", Name: ").append(animal.getName())
                    .append(", Breed: ").append(animal.getBreed())
                    .append(", Gender: ").append(animal.getGender())
                    .append(", Age: ").append(animal.getAge())
                    .append("\n");
        }

        JOptionPane.showMessageDialog(this, animalListText.toString(), "Animal List", JOptionPane.INFORMATION_MESSAGE);
    }

    private void btnAddAnimalActionPerformed(ActionEvent evt) {
        // Implement the action for btnAddAnimal
        // Replace this with your actual implementation
        // Example: Assuming you have methods to get user input and add animal in your dao
        String id = JOptionPane.showInputDialog(this, "Enter Animal ID:");
        String name = JOptionPane.showInputDialog(this, "Enter Animal Name:");
        String breed = JOptionPane.showInputDialog(this, "Enter Animal Breed:");
        String gender = JOptionPane.showInputDialog(this, "Enter Animal Gender:");
        String age = JOptionPane.showInputDialog(this, "Enter Animal Age:");
    
        // Validate inputs and add animal
        if (id != null && name != null && breed != null && gender != null && age != null) {
            Animal newAnimal = new Animal(id, name, breed, gender, age);
    
            if (dao.addAnimal(newAnimal)) {
                JOptionPane.showMessageDialog(this, "Animal added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add animal.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid input. Please fill in all fields.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    

    private void btnAddSymptomsActionPerformed(ActionEvent evt) {
        // Implement the action for btnAddSymptoms
        // Replace this with your actual implementation
        // Example: Assuming you have methods to get user input and add symptoms in your dao
        String animalId = JOptionPane.showInputDialog(this, "Enter Animal ID:");
        String numSymptomsStr = JOptionPane.showInputDialog(this, "Enter Number of Symptoms:");

        if (animalId != null && numSymptomsStr != null) {
            try {
                int numSymptoms = Integer.parseInt(numSymptomsStr);
                List<String> symptoms = new ArrayList<>();

                for (int i = 0; i < numSymptoms; i++) {
                    String symptom = JOptionPane.showInputDialog(this, "Enter Symptom #" + (i + 1) + ":");
                    symptoms.add(symptom);
                }

                dao.addSymptoms(animalId, symptoms);
                JOptionPane.showMessageDialog(this, "Symptoms added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid input. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid input. Please fill in all fields.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnShowVetsActionPerformed(ActionEvent evt) {
        // Implement the action for btnShowVets
        // Replace this with your actual implementation
        // Example: Assuming you have a method getVetList() in your data access object (dao)
        List<Vet> vets = vetDAO.getVetList();
        StringBuilder vetListText = new StringBuilder("List of Vets:\n");

        for (Vet vet : vets) {
            vetListText.append("Name: ").append(vet.getName())
                    .append(", Specialization: ").append(vet.getSpecialization())
                    .append(", Contact: ").append(vet.getContact())
                    .append("\n");
        }

        JOptionPane.showMessageDialog(this, vetListText.toString(), "Vet List", JOptionPane.INFORMATION_MESSAGE);
    }

}

